[package]
name = "watchdag-test-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
watchdag = { path = "../../" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
