
# Global default watch config
[default]
watch = ["src/**/*.py", "scripts/**/*.sh"]
exclude = ["src/**/*tmp.py"]

# first -> second

[task.first]
cmd = "echo first"
watch = ["src/a/**"]          # only files under src/a
exclude = ["src/a/tests/**"]    # ignore tests for first
append_default_watch = true          # whether to also use the watch list in default.watch , defaults to false
append_default_exclude = true          # whether to also use the exclude list in default.exclude, defaults to false

[task.second]
cmd   = "echo second"
after = ["first"]                   # second runs after first
# B has no watch section -> uses global [watch]
