[config]
triggered_while_running_behaviour = "queue"  # default is queue, could alternatively be to exit the current dag and then rerun from where it was triggered with "cancel"
queue_length = 1 # queue length can be max one (default )




[task.A]
cmd = "sleep 3"
watch = ["src/test.txt"]


# to test: test both queue and retrigger behaviour 

