[task.A]
cmd = "echo starting; sleep 3; while true; do echo hello; sleep 3; done"
long_lived = true # commands that might take very long time or never finish
rerun = false # do not rerun command for subsequent runs, but attach to the same stdout as the first time it was started for progress_on_stdout, should default to true
trigger_on_stdout = "hello" # regex for making task A trigger on, 


[task.B]
cmd = "echo starting; sleep 3; while true; do echo hello; sleep 3; done"
long_lived = true
rerun = true # let the command run (since long_lived=true), but on subsequent run exit the last command and rerun it
progress_on_time = "3s"     # progress dag after 3 seconds 
after = ["A"]

# in this case task B should also be triggered after A 


