[default]
watch = [
  "texts/**.txt",
  "scripts/**/*.sh",
]
exclude = [
    "texts/**/*.tmp.txt"
]
use_hash = true # defaults to false, whether to create a hash of all the files to check if they have actually changed (not changed hash -> do not run command) 
#a text file should be create in current dir in .watchdag/hashes with key value pairs for tasks and the hashed contents of the watched files of the task

[task.A]
cmd = "echo A"
# here use_hash should be inherited from [default]

[task.B]
cmd   = "echo B"
use_hash = false # tasks can overwrite default


# to test: if contents have not changed, only B should run

